name: Update README on PR Review Announcement

on:
  issues:
    types: [opened, edited]

jobs:
  update-readme:
    if: contains(github.event.issue.labels.*.name, 'announcement')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install PyGithub python-dateutil
        
      - name: Make script executable
        run: chmod +x .github/scripts/update_readme.py
        
      - name: Update README with new PR review info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          REPO: ${{ github.repository }}
        run: |
          python .github/scripts/update_readme.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "Update README with PR Review Club info from #${{ github.event.issue.number }}"
          git push